### ISSUE TITLE
python: profile-related issues

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/CLANG-packages#11]
1. Failures with --with-lto due to unknown compiler flags.
2. Without --with-lto, linker error:
 ```
lld-link: error: undefined symbol: ___llvm_profile_counter_bias
>>> referenced by libclang_rt.profile-i386.a(InstrProfilingFile.c.obj):(___llvm_profile_initialize_file)
>>> referenced by libclang_rt.profile-i386.a(InstrProfilingFile.c.obj):(___llvm_profile_initialize)
>>> referenced by libclang_rt.profile-i386.a(InstrProfilingFile.c.obj):(_relocateCounters)
```

**Comment by mati865** [comment]
Why would Python even use profiler?
Second question since I don't have i686 build, what is the output from `$ llvm-nm /clang32/lib/clang/11.0.0/lib/windows/libclang_rt.profile-i686.a | grep __llvm_profile_counter_bias`?

**Comment by jeremyd2019** [comment]
It's actually `libclang_rt.profile-i386.a`.  Silly compiler-rt, does it really support back to the 386?

```
llvm-nm /clang32/lib/clang/11.0.0/lib/windows/libclang_rt.profile-i386.a | grep __llvm_profile_counter_bias
00000000 D .weak.___llvm_profile_counter_bias.default
00000000 W ___llvm_profile_counter_bias
         U ___llvm_profile_counter_bias
```

**Comment by mati865** [comment]
My bad, compiler builtins (doesn't matter if it's libgcc or compiler-rt) don't use any instructions beyond i386 so they use single i386 for all iX86...

> `U ___llvm_profile_counter_bias`

I don't have enough knowledge about weak symbols on Windows but this doesn't seem right for me.

**Comment by jeremyd2019** [comment]
for comparison, from existing mingw-w64-i686 package:
```
llvm-nm /mingw32/lib/clang/11.0.0/lib/windows/libclang_rt.profile-i386.a | grep __llvm_profile_counter_bias
00000000 D .weak.___llvm_profile_counter_bias.
         w ___llvm_profile_counter_bias
         U ___llvm_profile_counter_bias
```

**Comment by mati865** [comment]
> for comparison, from existing mingw-w64-i686 package:

Those look even worse because BFD doesn't handle weak symbols properly for MinGW.
We might need to backport https://github.com/llvm/llvm-project/commit/879c1db5d24dcb0ac03f9f6282a09996ff3dc291, I can test it tomorrow with x86_64 since this symbol looks there equally bad as on i686.

**Comment by jeremyd2019** [comment]
#13 seems to have fixed the linking issue, but python has other issues now that it can run.

**Comment by mati865** [comment]
I have no clue about `OSError: invalid Python installation: unable to open .../src/build-i686/PC/pyconfig.h (No such file or directory)`.

`TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`: one of variables is null, presumably `flags`?

**Comment by lazka** [comment]
afair, the build writes some things into `_sysconfigdata__win32_.py` which is then re-used during module builds. So likely some things are missing in that file.

**Comment by jeremyd2019** [comment]
> afair, the build writes some things into `_sysconfigdata__win32_.py` which is then re-used during module builds. So likely some things are missing in that file.

I saw that file and it looked pretty full...  However, given the issue with pyconfig.h, I guess that it may just be in the wrong location for some reason 😕

**Comment by jeremyd2019** [comment]
In any event, I think #13 fixed the original issue and I really should (have) opened a new issue for this.

**Comment by mati865** [comment]
Thanks for testing, I'll merge it then.
