### ISSUE TITLE
Bootstrapping MSYS2 with Clang?

### ISSUE THREAD

**Issue by teepean** [msys2/CLANG-packages#12]
A slightly noob question: how would one go about bootstrapping MSYS2 with Clang? I have almost no experience with Pacman or makepkg so if anyone would give some pointers. 

Thanks!

**Comment by mati865** [comment]
First you'd have to port Clang/LLVM to have proper MSYS target. Ad hoc packages that was added in https://github.com/msys2/MSYS2-packages/tree/master/clang doesn't even have proper C++ support and building code in debug mode with it is buggy.
It's non-goal for me but feel free to do what you want.

**Comment by teepean** [comment]
I might have phrased incorrectly: I want to bootstrap MSYS2/Clang with Mingw-w64 as the target.

**Comment by jeremyd2019** [comment]
for x86_64-w64-mingw32 (or i686-w64-mingw32 replacing 64 with 32 below), currently:
1. edit /etc/msystem to add CLANG64 like MINGW64
2. start an MSYS2 login shell with MSYSTEM=CLANG64
3. build and install the packages in this repo in dependency order.
4. start trying to build packages from MINGW-packages in dependency order

Step 4 is the most problematic.

I have been building packages with a command of the form
`MSYSTEM=CLANG64 makepkg --config /etc/makepkg_clang64.conf --noconfirm --noprogressbar --nocheck --syncdeps --rmdeps --cleanbuild`

**Comment by teepean** [comment]
Thank you!
