### ISSUE TITLE
python: missing time.mktime

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/CLANG-packages#21]
The configure test in python for mktime uses defines, which prevents the inline functions in time.h from being used.  It appears that there is a `mktime` symbol defined in msvcrt, but not in ucrt, which results in the configure test failing, and the time module lacking the mktime function.

**Comment by jeremyd2019** [comment]
It looks like `export ac_cv_func_mktime=yes` allows python to build, and include `time.mktime`, so it's just a matter of the configure test screwing up.  It makes me wonder how many other functions might be missed by configure.  I am thinking I should diff the results from configure on a msvcrt vs ucrt runtime.

**Comment by jeremyd2019** [comment]
I diffed the python config.log from a clang/aarch64 build and a gcc/x86_64 build, and saw no other unexpected differences (mostly from lack of ncurses, #4)

**Comment by lazka** [comment]
time.mktime is also missing with ucrt

**Comment by jeremyd2019** [comment]
I don't know whether this is more properly addressed in the configure script or in mingw-w64 providing an export.

**Comment by jeroen** [comment]
Is this a bug in mingw-w64? It should be there? https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/mktime-mktime32-mktime64?view=msvc-160

**Comment by jeremyd2019** [comment]
Perhaps.  It is present as an inline function in a header, but python's `configure` script tries to see if it can link to it, without headers.  That MS doc specifies that mktime should be an inline function.

**Comment by Biswa96** [comment]
Try to create a simple C program to reproduce the issue.

**Comment by jeremyd2019** [comment]
I'm talking about a configure test... Those do create simple C programs, but probably not exactly what you had in mind.

[python-mktime-check.txt](https://github.com/msys2/CLANG-packages/files/6214188/python-mktime-check.txt)

**Comment by Biswa96** [comment]
Hmm... This seems to be missing from mingw-w64. The M$ documentation does not reveal everything (as usual). msvcrt.dll exports all mktime, _mktime32 and _mktime64. Whereas ucrtbase.dll exports only _mktime32 and _mktime64 but not mktime. So, internally the msvc library aliases mktime to another function. Whereas mingw-w64 aliases mktime in header file not in library. Can you create an issue in mingw-w64 mailing list?

**Comment by lazka** [comment]
somewhat related, `AC_CHECK_FUNC (ctime)` and `AC_CHECK_FUNC (time)` fail for https://packages.msys2.org/base/mingw-w64-cunit

**Comment by jeremyd2019** [comment]
https://sourceforge.net/p/mingw-w64/mailman/message/37251001/

**Comment by lazka** [comment]
`localtime` is also affected

**Comment by jeremyd2019** [comment]
Commits which should fix this have been applied to mingw-w64 upstream.

**Comment by jeremyd2019** [comment]
I've confirmed that the original issue with python not detecting mktime is fixed.  I assume time/localtime would be detected now also as they were also added to the def files.
