### ISSUE TITLE
Notice: github actions token are now read only by default for this org

### ISSUE THREAD

**Issue by lazka** [msys2/CLANG-packages#38]
@jeremyd2019 if you want your workflows to be able to create releases and upload assets you need to do something like https://github.com/msys2/msys2-autobuild/commit/e779c2595f36a5e4c2016cf11f22efad82d0b080 (works on the top level as well as at the job level)

I assume forks are unaffected.

**Comment by jeremyd2019** [comment]
I changed the settings on my fork explicitly, to verify that the permissions entry works as expected before pushing here.

**Comment by jeremyd2019** [comment]
Hopefully we won't actually need to run these workflows again anyway...
