### ISSUE TITLE
gnutls does not seem to export the ffdhe and srp generators correctly.

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/CLANG-packages#39]
Huh ?!? strange, gnutls does not seem to export the ffdhe and srp generators correctly.

_Originally posted by @revelator in https://github.com/msys2/MINGW-packages/issues/8427#issuecomment-826142031_

This issue was extracted from that rather large thread

**Comment by jeremyd2019** [comment]
> It looks like gnutls uses a complicated mechanism to determine what symbols should be exported (parsing nm -B output and generating a .def file), and that is missing DATA symbols on clang for some reason.

> ```shell
> nm -B ... | sed -n -e 's/^.*[ ]\([ABCDGISTW][ABCDGISTW]*\)[    ][      ]*_\([_A-Za-z][_A-Za-z0-9]*\)\{0,1\}$/\1 _\2 \2/p' | sed '/ __gnu_lto/d' | /usr/bin/sed -e '/^[BCDGRS][ ]/s/.*[ ]\([^ ]*\)/\1 DATA/;s/^.*[ ]__nm__\([^ ]*\)[ ][^ ]*/\1 DATA/;/^I[ ]/d;/^[AITW][ ]/s/.* //' | sort | uniq
> ```
> 
> It seems the first sed pattern is missing `R` in the character class `[ABCDGISTW]`. ~I don't know where this pattern comes from...~ libtool

> OK, I see...
> https://github.com/autotools-mirror/libtool/blob/master/m4/libtool.m4#L3942
> 
> but
> https://github.com/autotools-mirror/libtool/blob/master/m4/libtool.m4#L3972-L3976
> 
> So the fact that llvm's `nm -V` doesn't say 'GNU' (or in fact seem to be recognized at all) causes it to use a different pattern that doesn't include `R`
> 
> @mati865 ? Damn autotools again

**Comment by revelator** [comment]
agreed, it was getting a bit long.

further bugs -> flac++ error: undefined symbol: MIN MAX flac seems to use the old macro based min max, should possibly replace with std::min std::max or ?.

**Comment by mati865** [comment]
@mstorsjo WDYT should we patch libtool or llvm-nm to mimic gnu nm?

**Comment by mstorsjo** [comment]
> @mstorsjo WDYT should we patch libtool or llvm-nm to mimic gnu nm?

I think patching `llvm-nm -V` to print `GNU` sounds reasonable; there's lots of similar cases in the output of other tools too, see e.g. https://github.com/llvm/llvm-project/commit/523904133894888592a280ff7d0f0579418901f9, and `ld.lld --version` also includes the keyword `GNU` for this reason.

Patching libtool might be more straightforward in one sense, but patching the llvm tools is better in the cases where it's reasonable doable, as the libtool upstream isn't responsive.

**Comment by revelator** [comment]
True that would make things a bit easier going forward :).

Btw, i tried running autoreconf -fi on xapian core but it still fails with the exact same error so im not sure what else can be done.

**Comment by jeremyd2019** [comment]
I think the idea of splitting this into a new issue was to keep it to just the single issue

**Comment by revelator** [comment]
Oups sorry :)

**Comment by revelator** [comment]
as for gnutls i got around it temporarily by splitting the exports out of gnutls.h and putting the externs directly into the 2 source files
that are complaining about them. 
[0002-clang-compat.zip](https://github.com/msys2/CLANG-packages/files/6376391/0002-clang-compat.zip)

it works but is a butt ugly hack so should not really be used.

**Comment by jeremyd2019** [comment]
I'll post this here too, but it's still a fairly ugly hack...

heck, you might be able to make a wrapper shell script named `nm` next to nm.exe that handles the `-V` command line argument...

```bash
#!/usr/bin/env bash

for a; do
  if [[ "$a" == "-V" || "$a" == "--version" ]]; then
    echo "LLVM nm (like GNU)"
    exit 0
  fi
done

exec "$(dirname "${BASH_SOURCE[0]}")/nm.exe" "$@"
```

_Originally posted by @jeremyd2019 in https://github.com/msys2/MINGW-packages/issues/8427#issuecomment-828038500_

**Comment by jeremyd2019** [comment]
BTW, this same issue affects libidn

**Comment by revelator** [comment]
yep massive shot in the arm with that wrapper cool stuff :D

**Comment by jeremyd2019** [comment]
@Biswa96 - if you are looking at the gnutls issue, this has more information.  I think the best fix would be to patch llvm-nm to handle -V/--version and return something containing `GNU`.

**Comment by jeremyd2019** [comment]
Has anyone had time to at a patch adding `-V`/`--version` to llvm-nm?

**Comment by mstorsjo** [comment]
Try https://github.com/mstorsjo/llvm-project/commit/0e1e36098005b34ef7df3ca16310ae396483464a.patch. I haven't tested it with libtool though; I would expect it to pass the detection, but I don't know if the new codepaths in libtool that it unlocks all work as they should or if it starts assuming something that llvm-nm doesn't yet do.

**Comment by mstorsjo** [comment]
That patch to llvm-nm went upstream now, in https://github.com/llvm/llvm-project/commit/b42fb6811e25322f7e55d3f76fe13a6829202219 - with a few minor tweaks compared with the earlier version. Nothing of value to bother about for you though.
