### ISSUE TITLE
ncurses: tic fails to compile terminfo if built with clang

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/CLANG-packages#4]
This does not happen when built with gcc.  I tried with shorter paths, but got the same error.

```
mkdir -p /home/adminuser/MINGW-packages/mingw-w64-ncurses/pkg/mingw-w64-clang-i686-ncurses/clang32/share/tabset
DESTDIR=/home/adminuser/MINGW-packages/mingw-w64-ncurses/pkg/mingw-w64-clang-i686-ncurses \
prefix=/clang32 \
exec_prefix=/clang32 \
bindir=/clang32/bin \
top_srcdir=../../ncurses-6.2 \
srcdir=../../ncurses-6.2/misc \
datadir=/clang32/share \
ticdir=/clang32/share/terminfo \
source=terminfo.tmp \
cross_compiling=no \
/bin/sh ./run_tic.sh
** Building terminfo database, please wait...
Running tic to install /home/adminuser/MINGW-packages/mingw-w64-ncurses/pkg/mingw-w64-clang-i686-ncurses/clang32/share/terminfo ...

        You may see messages regarding extended capabilities, e.g., AX.
        These are extended terminal capabilities which are compiled
        using
                tic -x
        If you have ncurses 4.2 applications, you should read the INSTALL
        document, and install the terminfo without the -x option.

64/dumb: Invalid argument
"terminfo.tmp", line 304, terminal 'dumb': can't open C:\msys64\home\adminuser\MINGW-packages\mingw-w64-ncurses\pkg\mingw-w64-clang-i686-ncurses\clang32\share\terminfo/64/dumb
? tic could not build /home/adminuser/MINGW-packages/mingw-w64-ncurses/pkg/mingw-w64-clang-i686-ncurses/clang32/share/terminfo
make[1]: *** [Makefile:93: install.data] Error 1
```

**Comment by lazka** [comment]
Same with gcc+ucrt. I think I got it working by going into `run_tic.sh` after the build failed and forcing it to use /usr/bin/tic.. of course not ideal..

**Comment by jeremyd2019** [comment]
> There was space or something with dashes. I think I was able to solve it.

_Originally posted by @mati865 in https://github.com/msys2/MINGW-packages/discussions/7589#discussioncomment-261973_

if you could remember/find what you did to solve this...  it seems to be a ucrt thing not a clang-specific thing.

**Comment by jeremyd2019** [comment]
I did some debugging, and it seems to fail at:
https://github.com/mirror/ncurses/blob/1f7a36f/ncurses/tinfo/access.c#L136

I believe this test program shows the cause of the issue:
```c
#include <io.h>
#include <stdio.h>
#include <stddef.h>

int main(int argc, char ** argv)
{
  int ret = mkdir("64");
  printf("mkdir: %d (%d)\n", ret, errno);
  ret = access("64/", R_OK|W_OK);
  printf("access R_OK|W_OK: %d (%d)\n", ret, errno);
  ret = access("64/", R_OK|W_OK|X_OK);
  printf("access R_OK|W_OK|X_OK: %d (%d)\n", ret, errno);
  return 0;
}
```

On msvcrt-based mingw, all return 0.  On ucrt-based passing `X_OK` to `access` returns -1 (errno = EINVAL).

**Comment by jeremyd2019** [comment]
Reported to mingw-w64: https://sourceforge.net/p/mingw-w64/mailman/message/37257660/

**Comment by lazka** [comment]
the msvc docs suggest that this is expected. no mention of x_ok and error on invalid mode

**Comment by jeremyd2019** [comment]
ncurses itself masks out X_OK on MSVC.  https://github.com/mirror/ncurses/blob/1f7a36f/ncurses/tinfo/access.c#L44-L48  (_NC_MSC is defined if _MSC_VER is defined).  Unfortunately, msvcrt/ucrt != MSVC.  Maybe that ifdef needs to be patched to #ifdef _WIN32 or some such?

**Comment by gvanem** [comment]
> _NC_MSC is defined if _MSC_VER is defined

I fail to see which `clang` or `clang-cl` you're using. Not all of them has  `_MSC_VER` as a built-in.
E.g. my Cygwin `clang` does not have it. Try a `clang -dM -E - < NUL | grep _MSC_VER` to check.

**Comment by jeremyd2019** [comment]
clang from this repo, and from MINGW-packages.  Also gcc from MINGW-packages.  Neither define `_MSC_VER`.

**Comment by lazka** [comment]
I see unguarded calls to access() in ncurses with X_OK as well, so I went with `__USE_MINGW_ACCESS`: https://github.com/msys2/MINGW-packages/pull/8307

**Comment by jeremyd2019** [comment]
Confirmed msys2/MINGW-packages#8307 fixes this 🚀
