### ISSUE TITLE
libssp not available

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/CLANG-packages#40]
It seems to be buildable from GCC sources: https://github.com/mstorsjo/llvm-mingw/blob/master/build-libssp.sh.  Thinking about making a PKGBUILD based on that, only for clang* mingw_arch.  Thoughts @lazka @mstorsjo?

**Comment by mstorsjo** [comment]
Sounds good to me.

Longterm, I've considered reimplementing those bits within mingw-w64-crt; given that on many other platforms (glibc, Darwin), the platform libc comes with those functions, so cases where `-lssp` is missing isn't fatal. (It's also noticed e.g. if building with `-D_FORTIFY_SOURCE=<n>`, which requires `-lssp` on mingw but not on other platforms.) Most of the functions are fairly trivial. But it's not something I've actually gotten to...

**Comment by lazka** [comment]
`_FORTIFY_SOURCE` is a pain right now and we disable it everywhere because it needs patching upstream projects to expose "-lssp" via cmake/pkgconfig for static builds.

Any change in gcc/mingw-w64 that would make this go away would be very welcome.

**Comment by mati865** [comment]
> As for an extra "libssp", does clang have something similar to gcc-libs?

Libc++ and libunwind packages.

> Longterm, I've considered reimplementing those bits within mingw-w64-crt; given that on many other platforms (glibc, Darwin)

Coming from glibc I've been wondering why mingw-w64 CRT doesn't provide it. Anyway sounds good to provide it within mingw-w64.

**Comment by jeremyd2019** [comment]
I thought about adding it to the clang PKGBUILD but it's soo large already, hard to deal with.  I'm going to try making it a stand-alone PKGBUILD first.
