### ISSUE TITLE
workaround for --version-script

### ISSUE THREAD

**Issue by revelator** [msys2/CLANG-packages#41]
took me a load of reading but if version-script is used as a linker script you can replace it with lld's Map flag eg.
-Wl,--version-script,script -> -Wl,--Map=script tested it building appstream-glib and it works :)

**Comment by mati865** [comment]
`version-script` is an input file while `.map` is output file used **only** to debug the linker:
```
$ ld.lld --help | rg map
  --Map=<value>         Output a linker map
```

**Comment by revelator** [comment]
yep though atleast it allows us building appstream-glib even if it is a bit useless.

**Comment by mati865** [comment]
You can comment it out entirely and it won't change anything compared to `--Map`.

**Comment by revelator** [comment]
true though maybe a better approach would be to just restrict it for gcc use ?.

**Comment by mati865** [comment]
Naturally, disabling version script will often have negative consequences even if small.
