### ISSUE TITLE
backport llvm-windres?

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/CLANG-packages#44]
I don't want to hold up the current pull request, so I'm documenting this here.  Maybe it would be possible to backport llvm-windres in place of the wrapper?  I think that's https://reviews.llvm.org/D100756.  The wrapper is causing me issues with hacking together cross-compilation scripts in https://github.com/msys2/MINGW-packages/discussions/8736

**Comment by jeremyd2019** [comment]
This seems to be https://github.com/llvm/llvm-project/commit/f8de9aaef2f472ad7572748582444083d31d5a95, but it looks like it would probably also depend on https://github.com/llvm/llvm-project/commit/64bc44f5ddfb6da4b6a8b51ea9a03f8772b3ae95 being applied first.

**Comment by mati865** [comment]
It's series of 4 patches IIRC and I have feeling they will depend on someyhing else.
They would probably improve comaptibility with GNU windres, we could do something similar to what I did with filesystem patches and merge all RC changes between LLVM 12 and trunk into one patch.

**Comment by mati865** [comment]
Here is untested patch for all llvm-rc changes since LLVM 12 release:
[0000-windres.patch.txt](https://github.com/msys2/CLANG-packages/files/6526177/0000-windres.patch.txt)

**Comment by jeremyd2019** [comment]
Thanks.  It applies and builds cleanly at least.  One thing that's my fault when I was getting the windres wrapper working:
  ```diff
  [MSYS2 CI] mingw-w64-clang: File listing diff for mingw-w64-clang-i686-llvm-12.0.0-6-any.pkg.tar.zst
  
  --- /dev/fd/63	2021-05-24 03:34:52.000000000 +0000
  +++ /dev/fd/62	2021-05-24 03:34:52.000000000 +0000
  @@ -9,7 +9,6 @@
   /clang32/bin/dsymutil.exe
   /clang32/bin/dwp.exe
   /clang32/bin/FileCheck.exe
  -/clang32/bin/i686-w64-mingw32-windres.exe
   /clang32/bin/KillTheDoctor.exe
   /clang32/bin/libLLVM.dll
   /clang32/bin/libLTO.dll
  @@ -2000,8 +1999,6 @@
   /clang32/share/licenses/
   /clang32/share/licenses/llvm/
   /clang32/share/licenses/llvm/LICENSE
  -/clang32/share/licenses/llvm-windres/
  -/clang32/share/licenses/llvm-windres/LICENSE
   /clang32/share/llvm/
   /clang32/share/llvm/cmake/
   /clang32/share/llvm/cmake/modules/
```

I installed that prefixed alias because that was how the wrapper determined the target, before I started setting `DEFAULT_TARGET` preprocessor symbol.  Hopefully nobody cares that it goes away now.

Will try building some packages with it and see what happens

**Comment by jeremyd2019** [comment]
- windows-default-manifest: doesn't help, still broken
- gettext: still works
- python: fails
  ```
  llvm-rc: Error in ICON statement (ID 1):
  Stream Error: The stream is too short to perform the requested operation.
  ```

**Comment by jeremyd2019** [comment]
Downgrading to 12.0.0-5 and python builds successfully, so this patch seems responsible

**Comment by mstorsjo** [comment]
> * python: fails
>   ```
>   llvm-rc: Error in ICON statement (ID 1):
>   Stream Error: The stream is too short to perform the requested operation.
>   ```

I tried a cross build of python, with llvm-windres available, and it built fine - and from some looking into what it built, it does look like it built some resource files that contain ICON types. I didn't try building on native windows though.

**Comment by jeremyd2019** [comment]
If it only happens on Windows, and it's a stream size issue, it may be that something is not accessing the icon in "binary mode" and getting `\x0d\x0a` translated into just `\x0a`.  That was my first thought when it said the icon was too short.

**Comment by mstorsjo** [comment]
> If it only happens on Windows, and it's a stream size issue, it may be that something is not accessing the icon in "binary mode" and getting `\x0d\x0a` translated into just `\x0a`. That was my first thought when it said the icon was too short.

Hmm, that's a good hunch - but the actual resource compiler part of it should be the same, regardless if the windres wrapper invokes it as llvm-rc, or if invoked directly as llvm-windres...

**Comment by mstorsjo** [comment]
I tried reproducing this on msys2 too; I replaced the windres executables in the `clang64` subsystem with upstream llvm-windres (cross-built) and ran `MINGW_ARCH=clang64 makepkg-mingw -sCLf` in MINGW-packages/mingw-w64-python, and that also succeeded.

**Comment by jeremyd2019** [comment]
Well then WTF?  Something missing from @mati865's backport patch?

**Comment by mstorsjo** [comment]
> Well then WTF? Something missing from @mati865's backport patch?

I wouldn't think so, probably something else in the whole environment maybe...

For someone unfamiliar with msys package management and all - what would be the most straightforward way to reproduce your situation? Start with the current public clang64 setup, add the bundled patch to the llvm (how do I build that one, is it the regular llvm package from MINGW-packages, or a special one for the clang64 target?), and then rebuild python (using the commands I had used above, or something else)?

**Comment by jeremyd2019** [comment]
1. Apply https://github.com/jeremyd2019/MINGW-packages/commit/2213dc9a339575adee1403bc0e7e3cf70195b4d0
2. build mingw-w64-clang for clang64
3. Install resulting packages
4. attempt to build mingw-w64-python for clang64.

Note that I've seen weird clang crashes with `--log`/`-L` option (piping build output through `tee`, #3). Also, I usually use `--nocheck` with makepkg (checks are not really all that well maintained or expected to succeed).

**Comment by mstorsjo** [comment]
> 1. Apply [jeremyd2019/MINGW-packages@2213dc9](https://github.com/jeremyd2019/MINGW-packages/commit/2213dc9a339575adee1403bc0e7e3cf70195b4d0)
> 2. build mingw-w64-clang for clang64
> 3. Install resulting packages
> 4. attempt to build mingw-w64-python for clang64.
> 
> Note that I've seen weird clang crashes with `--log`/`-L` option (piping build output through `tee`, #3). Also, I usually use `--nocheck` with makepkg (checks are not really all that well maintained or expected to succeed).

Ok, thanks, with that procedure I was able to reproduce the issue. I'll try to look into it a bit later then...

**Comment by mstorsjo** [comment]
> If it only happens on Windows, and it's a stream size issue, it may be that something is not accessing the icon in "binary mode" and getting `\x0d\x0a` translated into just `\x0a`. That was my first thought when it said the icon was too short.

> Well then WTF? Something missing from @mati865's backport patch?

Ok it does indeed seem like this is it: It's not about llvm-windres vs windres-wrapper+llvm-rc, because after the bundled backports in that patch, llvm-rc also fails on building a rc file that includes an icon in the same way. (You can test it with a simple rc file like `100 ICON "icon.ico"` and executing `llvm-rc icon.rc`.) The first of the backported patches, "[PATCH 1/6] [NFC] Reordering parameters in getFile and getFileOrSTDIN", sounds like it could be breaking something if applied partially/incorrectly (or maybe it did break something and there was a separate fixup patch elsewhere that has to be picked too).

**Comment by mstorsjo** [comment]
0012-windres.patch seems to contain an incomplete backport of https://github.com/llvm/llvm-project/commit/c83cd8feef7eb8319131d968bb8c94fdc8dbb6a6; it backports the changes to llvm-rc but not the changes to the API that it calls (and due to implicit casting rules, the compiler doesn't seem to mind).

**Comment by jeremyd2019** [comment]
That commit seems pretty invasive, in that it touches a lot of different places.  I wonder if it wouldn't be better to exclude that.  It looks like only one subsequent patch touches code changed by that.  But that would probably be error prone for future patches...

**Comment by jeremyd2019** [comment]
https://github.com/jeremyd2019/MINGW-packages/commit/9868b85daa8291882b5d84fbf0bdbc3c7e888ada see if that builds and  works

**Comment by jeremyd2019** [comment]
That version of the patch built (after updating sha256sums in PKGBUILD, oops!) and was able to build python.

**Comment by mati865** [comment]
I thought `git format-patch` would take whole commits when ran inside subdirectory, my bad!
Thank you for fixing the backport while I was unavailable.
