### ISSUE TITLE
pkg-config: included glib doesn't support arm/aarch64 Windows

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/CLANG-packages#7]
The copy of glib included in pkg-config apparently doesn't support arm/aarch64.  This is probably also going to be an issue with stand-alone glib.  The following hack got it building, but it needs to be cleaned up so as not to break other platforms.

```diff
diff -ur glib/glib/gbacktrace.h glib/glib/gbacktrace.h
--- glib/glib/gbacktrace.h      2016-04-11 14:39:26.000000000 -0700
+++ glib/glib/gbacktrace.h      2021-01-03 21:45:16.025393700 -0800
@@ -58,7 +58,7 @@
 #elif defined (__alpha__) && !defined(__osf__) && defined (__GNUC__) && __GNUC__ >= 2
 #  define G_BREAKPOINT()        G_STMT_START{ __asm__ __volatile__ ("bpt"); }G_STMT_END
 #else   /* !__i386__ && !__alpha__ */
-#  define G_BREAKPOINT()        G_STMT_START{ raise (SIGTRAP); }G_STMT_END
+#  define G_BREAKPOINT()        G_STMT_START{ __builtin_trap(); }G_STMT_END
 #endif  /* __i386__ */

 G_END_DECLS
diff -ur glib/glib/valgrind.h glib/glib/valgrind.h
--- glib/glib/valgrind.h        2016-04-11 14:39:26.000000000 -0700
+++ glib/glib/valgrind.h        2021-01-03 21:45:16.009865100 -0800
@@ -124,7 +124,7 @@
 #  define PLAT_x86_darwin 1
 #elif defined(__APPLE__) && defined(__x86_64__)
 #  define PLAT_amd64_darwin 1
-#elif defined(__MINGW32__) || defined(__CYGWIN32__) \
+#elif defined(__CYGWIN32__) \
       || (defined(_WIN32) && defined(_M_IX86))
 #  define PLAT_x86_win32 1
 #elif defined(__linux__) && defined(__i386__)
```

**Comment by lazka** [comment]
Note that glib there is an old version, and we use pkgconf now

**Comment by jeremyd2019** [comment]
I opted to try pkg-config instead of pkgconf because the latter uses cmake in its PKGBUILD, and I have not yet gotten enough prerequisites together for that.  I did see that pkgconf also has a configure script, and was thinking of trying that to see if pkgconf could be installed before cmake.

**Comment by jeremyd2019** [comment]
It appears configure/make build succeeds for pkgconf, at least on i686, and seems to be much simpler than pkg-config.

**Comment by jeremyd2019** [comment]
Should this be transferred, or just closed and declare pkg-config is not supported on arm?

**Comment by lazka** [comment]
> Should this be transferred, or just closed and declare pkg-config is not supported on arm?

not supporting it seems fine to me. It's still abandoned upstream and we start to depend on pkgconf only features like Cflags.private now.

**Comment by jeremyd2019** [comment]
I guess since I transferred all the other closed issues this one can too.
